### ISSUE TITLE
Install command doesn't work

### ISSUE THREAD

**Issue by TrapaCivet** [itzmeanjan/tgnize#4]
I'm not sure if this is the correct place.  I am pretty sure the problem is on my end and being new to pip and installing things via pip, 

But.  here goes.
If I attempt to install using the suggested command I get this:
```
trapa@regdev3:~$ pip3 install tgnize --user
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
ERROR: Could not find a version that satisfies the requirement tgnize
ERROR: No matching distribution found for tgnize
trapa@regdev3:~$

```

And if I attempt to install via pip3 I get this:
```
trapa@regdev3:~$ pip3 install tgnize
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement tgnize
ERROR: No matching distribution found for tgnize
```

Any help would be appriciated.

**Comment by itzmeanjan** [comment]
Hello @TrapaCivet , looks like you need to install `tgnize` using 

```bash
python3 -m pip install tgnize
```

**Comment by TrapaCivet** [comment]
Unfortunatly, same result.
`
trapa@regdev3:~$ python3 -m pip install tgnize
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement tgnize
ERROR: No matching distribution found for tgnize
`

**Comment by itzmeanjan** [comment]
First make sure you've installed Python _>=3.7_, then run

```bash
python3 -m pip install tgnize --user
```

**Comment by TrapaCivet** [comment]
Thanks for all the help!,  For others otu there my problem was that i was running python 3.6 and this needs python 3.7

This url helped me upgrade
[https://www.itsupportwale.com/blog/how-to-upgrade-to-python-3-7-on-ubuntu-18-10/](url)

**Comment by itzmeanjan** [comment]
Happy to learn, you were able to resolve it.
